### ISSUE TITLE
tslint: Why double quote-mark?

### ISSUE THREAD

**Issue by sondreb** [Azure/service-fabric-explorer#22]
It's very unusual to use double quote-marks in JavaScript/TypeScript source, what is the rational to go with double as oppose to single?

Keep forgetting this and get compile errors ;-)

**Comment by stevshan** [comment]
Hey @sondreb, actually using double quote-marks or single quote-marks is depending on the project. Single quote-marks are suggested for UI/HTML related works. For SFX-Standone, since the codes are mainly non-UI/HTML related but logics related,  using quote-marks are fine and more natural for the developers. 

Thanks.
